<?php
if (function_exists('acf_add_local_field_group')) {
	acf_add_local_field_group(array(
		'key' => 'recruit_page_acf',
		'title' => '求人情報のカスタムフィールド',
		'fields' => [
			//== 企業一覧 ====
			[
				'key' => 'recruit_companies_tab',
				'label' => '企業一覧',
				'name' => 'recruit_companies_tab',
				'type' => 'tab',
			],
			[
				'key' => 'recruit_companies_section_title',
				'label' => 'セクション リード文章',
				'name' => 'recruit_companies_section_title',
				'type' => 'textarea',
				'required' => 1,
				'instructions' => "1行あたり17~25文字程度を推奨。",
			],
			[
				'key' => 'recruit_companies',
				'label' => '企業一覧',
				'name' => 'recruit_companies',
				'type' => 'repeater',
				'layout' => 'block',
				'sub_fields' => [
					[
						'key' => 'recruit_company_img',
						'label' => '画像',
						'name' => 'recruit_company_img',
						'type' => 'image',
						'return_format' => 'url',
						'required' => 1,
						'instructions' => "横200px 縦70px程の画像推奨。",
					],
					[
						'key' => 'recruit_company_title',
						'label' => 'タイトル',
						'name' => 'recruit_company_title',
						'type' => 'text',
						'required' => 1,
						'instructions' => "推奨文字数 : 20文字",
					],
					[
						'key' => 'recruit_company_department',
						'label' => '担当部署',
						'name' => 'recruit_company_department',
						'type' => 'text',
						'maxlength' => 20,
						'instructions' => "最大20文字",
					],
					[
						'key' => 'recruit_company_in_charge',
						'label' => '担当者',
						'name' => 'recruit_company_in_charge',
						'maxlength' => 20,
						'instructions' => "最大20文字",
						'type' => 'text',
					],
					[
						'key' => 'recruit_company_text',
						'label' => '本文',
						'name' => 'recruit_company_text',
						'type' => 'textarea',
						'required' => 1,
						'instructions' => "推奨文字数 : 40文字",
					],
				],
			],

			//== 求人情報セクション ====
			[
				'key' => 'recruit_tags_tab',
				'label' => '求人情報セクション',
				'name' => 'recruit_tags_tab',
				'type' => 'tab',
			],
			[
				'key' => 'recruit_tags_section_title',
				'label' => '求人情報セクションタイトル',
				'name' => 'recruit_tags_section_title',
				'type' => 'wysiwyg',
				'tabs' => 'visual',
				'toolbar' => 'bold_only',
				'media_upload' => 0,
				'instructions' => '太字（Ctrl + B）の箇所が黄色文字になります。',
				'required' => 1,
			],
			[
				'key' => 'recruit_tags',
				'label' => '求人情報タグ一覧',
				'name' => 'recruit_tags',
				'type' => 'repeater',
				'sub_fields' => [
					[
						'key' => 'recruit_tag',
						'label' => 'タグ名',
						'name' => 'recruit_tag',
						'type' => 'text',
						'required' => 1,
						'maxlength' => 25,
						'instructions' => "最大25文字まで入力可能（＊10文字以下推奨）",
					]
				],
			],
			//== 求人情報一覧 ====
			[
				'key' => 'recruit_cards_tab',
				'label' => '求人情報一覧',
				'name' => 'recruit_cards_tab',
				'type' => 'tab',
			],
			[
				'key' => 'recruit_cards',
				'label' => '求人情報一覧',
				'name' => 'recruit_cards',
				'type' => 'repeater',
				'layout' => 'block',
				'sub_fields' => [
					[
						'key' => 'recruit_card_title',
						'label' => 'タイトル',
						'name' => 'recruit_card_title',
						'type' => 'wysiwyg',
						'tabs' => 'visual',
						'toolbar' => 'bold_only',
						'media_upload' => 0,
						'instructions' => '太字（Ctrl + B）の箇所が黄色文字になります。',
						'required' => 1,
						],
						[
							'key' => 'recruit_card_img',
							'label' => '画像',
							'name' => 'recruit_card_img',
							'type' => 'image',
							'return_format' => 'url',
							'required' => 1,
							'instructions' => '推奨画像サイズ : 横380px 縦240px',
					],
					[
						'key' => 'recruit_card_tags',
						'label' => 'タグ一覧',
						'name' => 'recruit_card_tags',
						'type' => 'repeater',
						'sub_fields' => [
							[
								'key' => 'recruit_card_tag',
								'label' => 'タグ',
								'name' => 'recruit_card_tag',
								'type' => 'text',
								'required' => 1,
								'maxlength' => 25,
								'instructions' => "最大25文字まで入力可能（推奨文字数 : 10文字以下）",
							]
						],
					],
					[
						'key' => 'recruit_card_heading',
						'label' => '見出し',
						'name' => 'recruit_card_heading',
						'type' => 'text',
						'required' => 1,
						'maxlength' => 20,
						'instructions' => "最大20文字まで入力可能（推奨文字数 : 10文字以下）",
					],
					[
						'key' => 'recruit_card_prev_income',
						'label' => '転職前年収',
						'name' => 'recruit_card_prev_income',
						'type' => 'number',
						'required' => 1,
						'append' => '万円',
						'max' => 9999,
						'instructions' => "最大4桁まで入力可能",
					],
					[
						'key' => 'recruit_card_next_income',
						'label' => '転職後年収',
						'name' => 'recruit_card_next_income',
						'type' => 'number',
						'required' => 1,
						'append' => '万円',
						'max' => 9999,
						'instructions' => "最大4桁まで入力可能",
					],
					[
						'key' => 'recruit_card_desc',
						'label' => '本文',
						'name' => 'recruit_card_desc',
						'type' => 'textarea',
						'required' => 1,
						'maxlength' => 100,
						'instructions' => "最大100文字まで入力可能（推奨文字数 : 80文字以下）",
					],
					[
						//== 外部リンクなのでblankを設定 ====
						'key' => 'recruit_card_link',
						'label' => 'URL',
						'name' => 'recruit_card_link',
						'type' => 'url',
					],
				],
			],
			//== 転職性恋事例 ====
			[
				'key' => 'recruit_case_tab',
				'label' => '転職成功事例',
				'name' => 'recruit_case_tab',
				'type' => 'tab',
			],
			[
				'key' => 'recruit_case_section_title',
				'label' => 'セクションタイトル',
				'name' => 'recruit_case_section_title',
				'type' => 'textarea',
				'instructions' => 'sp時には改行が消え、左揃えになります。<br>1行あたり17~25文字程度を推奨。',
			],
			[
				'key' => 'recruit_case_posts',
				'label' => '転職成功事例 一覧',
				'name' => 'recruit_case_posts',
				'type' => 'relationship',
				'post_type' => 'case',
				'required' => 1,
			],
			//== その他 ====
			[
				'key' => 'recruit_others_tab',
				'label' => 'その他',
				'name' => 'recruit_others_tab',
				'type' => 'tab',
			],
			[
				'key' => 'recruit_others_title',
				'label' => 'セクションタイトル',
				'name' => 'recruit_others_title',
				'type' => 'text',
				'required' => 1,
				'instructions' => "推奨文字数 : 7~15文字",
			],
			[
				'key' => 'recruit_others_text',
				'label' => 'セクション リード文章',
				'name' => 'recruit_others_text',
				'type' => 'textarea',
				'required' => 1,
				'instructions' => "推奨文字数 : 1行あたり17~25文字",
			],
			[
				'key' => 'recruit_others',
				'label' => 'カード一覧',
				'name' => 'recruit_others',
				'type' => 'repeater',
				'layout' => 'block',
				'instructions' => '入力がない場合はセクションごと消えます。',
				'sub_fields' => [
					[
						'key' => 'recruit_other_img',
						'label' => '画像',
						'name' => 'recruit_other_img',
						'type' => 'image',
						'return_format' => 'url',
						'required' => 1,
						'instructions' => "推奨画像サイズ : 横250px 縦150px",
					],
					[
						'key' => 'recruit_other_text',
						'label' => 'テキスト',
						'name' => 'recruit_other_text',
						'type' => 'textarea',
						'required' => 1,
						'instructions' => "推奨文字数 : 30~40文字",
					],
					[
						//== 外部リンクなのでblankを設定 ====
						'key' => 'recruit_other_link',
						'label' => 'リンク',
						'name' => 'recruit_other_link',
						'type' => 'url',
					],
				],
			],
		],
		'location' => array(
			array(
				array(
					'param' => 'page',
					'operator' => '==',
					'value' => get_page_by_path('recruit')->ID,
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
	));
}
